package com.bluestrom.gao.explorersogoupics.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bluestrom.gao.explorersogoupics.pojo.SogouPicPojo;

import com.bluestrom.gao.explorersogoupics.greendao.SogouPicPojoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sogouPicPojoDaoConfig;

    private final SogouPicPojoDao sogouPicPojoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sogouPicPojoDaoConfig = daoConfigMap.get(SogouPicPojoDao.class).clone();
        sogouPicPojoDaoConfig.initIdentityScope(type);

        sogouPicPojoDao = new SogouPicPojoDao(sogouPicPojoDaoConfig, this);

        registerDao(SogouPicPojo.class, sogouPicPojoDao);
    }
    
    public void clear() {
        sogouPicPojoDaoConfig.clearIdentityScope();
    }

    public SogouPicPojoDao getSogouPicPojoDao() {
        return sogouPicPojoDao;
    }

}
