package com.bluestrom.gao.explorersogoupics.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bluestrom.gao.explorersogoupics.pojo.SogouPicPojo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SOGOU_PIC_POJO".
*/
public class SogouPicPojoDao extends AbstractDao<SogouPicPojo, Long> {

    public static final String TABLENAME = "SOGOU_PIC_POJO";

    /**
     * Properties of entity SogouPicPojo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Did = new Property(1, int.class, "did", false, "DID");
        public final static Property ThumbUrl = new Property(2, String.class, "thumbUrl", false, "THUMB_URL");
        public final static Property Thumb_width = new Property(3, int.class, "thumb_width", false, "THUMB_WIDTH");
        public final static Property Thumb_height = new Property(4, int.class, "thumb_height", false, "THUMB_HEIGHT");
        public final static Property SthumbUrl = new Property(5, String.class, "sthumbUrl", false, "STHUMB_URL");
        public final static Property Sthumb_width = new Property(6, int.class, "sthumb_width", false, "STHUMB_WIDTH");
        public final static Property Sthumb_height = new Property(7, int.class, "sthumb_height", false, "STHUMB_HEIGHT");
        public final static Property BthumbUrl = new Property(8, String.class, "bthumbUrl", false, "BTHUMB_URL");
        public final static Property Bthumb_width = new Property(9, int.class, "bthumb_width", false, "BTHUMB_WIDTH");
        public final static Property Bthumb_height = new Property(10, int.class, "bthumb_height", false, "BTHUMB_HEIGHT");
        public final static Property Pic_url = new Property(11, String.class, "pic_url", false, "PIC_URL");
        public final static Property Width = new Property(12, int.class, "width", false, "WIDTH");
        public final static Property Height = new Property(13, int.class, "height", false, "HEIGHT");
        public final static Property Size = new Property(14, int.class, "size", false, "SIZE");
        public final static Property Ori_pic_url = new Property(15, String.class, "ori_pic_url", false, "ORI_PIC_URL");
        public final static Property Ext_url = new Property(16, String.class, "ext_url", false, "EXT_URL");
        public final static Property Page_title = new Property(17, String.class, "page_title", false, "PAGE_TITLE");
        public final static Property Page_url = new Property(18, String.class, "page_url", false, "PAGE_URL");
        public final static Property Title = new Property(19, String.class, "title", false, "TITLE");
        public final static Property Tags = new Property(20, String.class, "tags", false, "TAGS");
        public final static Property Group_mark = new Property(21, String.class, "group_mark", false, "GROUP_MARK");
        public final static Property Group_index = new Property(22, int.class, "group_index", false, "GROUP_INDEX");
        public final static Property Publish_time = new Property(23, String.class, "publish_time", false, "PUBLISH_TIME");
        public final static Property Surr1 = new Property(24, String.class, "surr1", false, "SURR1");
        public final static Property Surr2 = new Property(25, String.class, "surr2", false, "SURR2");
        public final static Property Category = new Property(26, String.class, "category", false, "CATEGORY");
        public final static Property Weight = new Property(27, int.class, "weight", false, "WEIGHT");
        public final static Property Deleted = new Property(28, int.class, "deleted", false, "DELETED");
        public final static Property WapLink = new Property(29, String.class, "wapLink", false, "WAP_LINK");
        public final static Property WebLink = new Property(30, String.class, "webLink", false, "WEB_LINK");
    }

    private final PicsTagsConvert tagsConverter = new PicsTagsConvert();

    public SogouPicPojoDao(DaoConfig config) {
        super(config);
    }
    
    public SogouPicPojoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SOGOU_PIC_POJO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DID\" INTEGER NOT NULL ," + // 1: did
                "\"THUMB_URL\" TEXT," + // 2: thumbUrl
                "\"THUMB_WIDTH\" INTEGER NOT NULL ," + // 3: thumb_width
                "\"THUMB_HEIGHT\" INTEGER NOT NULL ," + // 4: thumb_height
                "\"STHUMB_URL\" TEXT," + // 5: sthumbUrl
                "\"STHUMB_WIDTH\" INTEGER NOT NULL ," + // 6: sthumb_width
                "\"STHUMB_HEIGHT\" INTEGER NOT NULL ," + // 7: sthumb_height
                "\"BTHUMB_URL\" TEXT," + // 8: bthumbUrl
                "\"BTHUMB_WIDTH\" INTEGER NOT NULL ," + // 9: bthumb_width
                "\"BTHUMB_HEIGHT\" INTEGER NOT NULL ," + // 10: bthumb_height
                "\"PIC_URL\" TEXT," + // 11: pic_url
                "\"WIDTH\" INTEGER NOT NULL ," + // 12: width
                "\"HEIGHT\" INTEGER NOT NULL ," + // 13: height
                "\"SIZE\" INTEGER NOT NULL ," + // 14: size
                "\"ORI_PIC_URL\" TEXT," + // 15: ori_pic_url
                "\"EXT_URL\" TEXT," + // 16: ext_url
                "\"PAGE_TITLE\" TEXT," + // 17: page_title
                "\"PAGE_URL\" TEXT," + // 18: page_url
                "\"TITLE\" TEXT," + // 19: title
                "\"TAGS\" TEXT," + // 20: tags
                "\"GROUP_MARK\" TEXT," + // 21: group_mark
                "\"GROUP_INDEX\" INTEGER NOT NULL ," + // 22: group_index
                "\"PUBLISH_TIME\" TEXT," + // 23: publish_time
                "\"SURR1\" TEXT," + // 24: surr1
                "\"SURR2\" TEXT," + // 25: surr2
                "\"CATEGORY\" TEXT," + // 26: category
                "\"WEIGHT\" INTEGER NOT NULL ," + // 27: weight
                "\"DELETED\" INTEGER NOT NULL ," + // 28: deleted
                "\"WAP_LINK\" TEXT," + // 29: wapLink
                "\"WEB_LINK\" TEXT);"); // 30: webLink
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SOGOU_PIC_POJO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SogouPicPojo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDid());
 
        String thumbUrl = entity.getThumbUrl();
        if (thumbUrl != null) {
            stmt.bindString(3, thumbUrl);
        }
        stmt.bindLong(4, entity.getThumb_width());
        stmt.bindLong(5, entity.getThumb_height());
 
        String sthumbUrl = entity.getSthumbUrl();
        if (sthumbUrl != null) {
            stmt.bindString(6, sthumbUrl);
        }
        stmt.bindLong(7, entity.getSthumb_width());
        stmt.bindLong(8, entity.getSthumb_height());
 
        String bthumbUrl = entity.getBthumbUrl();
        if (bthumbUrl != null) {
            stmt.bindString(9, bthumbUrl);
        }
        stmt.bindLong(10, entity.getBthumb_width());
        stmt.bindLong(11, entity.getBthumb_height());
 
        String pic_url = entity.getPic_url();
        if (pic_url != null) {
            stmt.bindString(12, pic_url);
        }
        stmt.bindLong(13, entity.getWidth());
        stmt.bindLong(14, entity.getHeight());
        stmt.bindLong(15, entity.getSize());
 
        String ori_pic_url = entity.getOri_pic_url();
        if (ori_pic_url != null) {
            stmt.bindString(16, ori_pic_url);
        }
 
        String ext_url = entity.getExt_url();
        if (ext_url != null) {
            stmt.bindString(17, ext_url);
        }
 
        String page_title = entity.getPage_title();
        if (page_title != null) {
            stmt.bindString(18, page_title);
        }
 
        String page_url = entity.getPage_url();
        if (page_url != null) {
            stmt.bindString(19, page_url);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(20, title);
        }
 
        String[] tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(21, tagsConverter.convertToDatabaseValue(tags));
        }
 
        String group_mark = entity.getGroup_mark();
        if (group_mark != null) {
            stmt.bindString(22, group_mark);
        }
        stmt.bindLong(23, entity.getGroup_index());
 
        String publish_time = entity.getPublish_time();
        if (publish_time != null) {
            stmt.bindString(24, publish_time);
        }
 
        String surr1 = entity.getSurr1();
        if (surr1 != null) {
            stmt.bindString(25, surr1);
        }
 
        String surr2 = entity.getSurr2();
        if (surr2 != null) {
            stmt.bindString(26, surr2);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(27, category);
        }
        stmt.bindLong(28, entity.getWeight());
        stmt.bindLong(29, entity.getDeleted());
 
        String wapLink = entity.getWapLink();
        if (wapLink != null) {
            stmt.bindString(30, wapLink);
        }
 
        String webLink = entity.getWebLink();
        if (webLink != null) {
            stmt.bindString(31, webLink);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SogouPicPojo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDid());
 
        String thumbUrl = entity.getThumbUrl();
        if (thumbUrl != null) {
            stmt.bindString(3, thumbUrl);
        }
        stmt.bindLong(4, entity.getThumb_width());
        stmt.bindLong(5, entity.getThumb_height());
 
        String sthumbUrl = entity.getSthumbUrl();
        if (sthumbUrl != null) {
            stmt.bindString(6, sthumbUrl);
        }
        stmt.bindLong(7, entity.getSthumb_width());
        stmt.bindLong(8, entity.getSthumb_height());
 
        String bthumbUrl = entity.getBthumbUrl();
        if (bthumbUrl != null) {
            stmt.bindString(9, bthumbUrl);
        }
        stmt.bindLong(10, entity.getBthumb_width());
        stmt.bindLong(11, entity.getBthumb_height());
 
        String pic_url = entity.getPic_url();
        if (pic_url != null) {
            stmt.bindString(12, pic_url);
        }
        stmt.bindLong(13, entity.getWidth());
        stmt.bindLong(14, entity.getHeight());
        stmt.bindLong(15, entity.getSize());
 
        String ori_pic_url = entity.getOri_pic_url();
        if (ori_pic_url != null) {
            stmt.bindString(16, ori_pic_url);
        }
 
        String ext_url = entity.getExt_url();
        if (ext_url != null) {
            stmt.bindString(17, ext_url);
        }
 
        String page_title = entity.getPage_title();
        if (page_title != null) {
            stmt.bindString(18, page_title);
        }
 
        String page_url = entity.getPage_url();
        if (page_url != null) {
            stmt.bindString(19, page_url);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(20, title);
        }
 
        String[] tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(21, tagsConverter.convertToDatabaseValue(tags));
        }
 
        String group_mark = entity.getGroup_mark();
        if (group_mark != null) {
            stmt.bindString(22, group_mark);
        }
        stmt.bindLong(23, entity.getGroup_index());
 
        String publish_time = entity.getPublish_time();
        if (publish_time != null) {
            stmt.bindString(24, publish_time);
        }
 
        String surr1 = entity.getSurr1();
        if (surr1 != null) {
            stmt.bindString(25, surr1);
        }
 
        String surr2 = entity.getSurr2();
        if (surr2 != null) {
            stmt.bindString(26, surr2);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(27, category);
        }
        stmt.bindLong(28, entity.getWeight());
        stmt.bindLong(29, entity.getDeleted());
 
        String wapLink = entity.getWapLink();
        if (wapLink != null) {
            stmt.bindString(30, wapLink);
        }
 
        String webLink = entity.getWebLink();
        if (webLink != null) {
            stmt.bindString(31, webLink);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SogouPicPojo readEntity(Cursor cursor, int offset) {
        SogouPicPojo entity = new SogouPicPojo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // did
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // thumbUrl
            cursor.getInt(offset + 3), // thumb_width
            cursor.getInt(offset + 4), // thumb_height
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // sthumbUrl
            cursor.getInt(offset + 6), // sthumb_width
            cursor.getInt(offset + 7), // sthumb_height
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // bthumbUrl
            cursor.getInt(offset + 9), // bthumb_width
            cursor.getInt(offset + 10), // bthumb_height
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // pic_url
            cursor.getInt(offset + 12), // width
            cursor.getInt(offset + 13), // height
            cursor.getInt(offset + 14), // size
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // ori_pic_url
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // ext_url
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // page_title
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // page_url
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // title
            cursor.isNull(offset + 20) ? null : tagsConverter.convertToEntityProperty(cursor.getString(offset + 20)), // tags
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // group_mark
            cursor.getInt(offset + 22), // group_index
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // publish_time
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // surr1
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // surr2
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // category
            cursor.getInt(offset + 27), // weight
            cursor.getInt(offset + 28), // deleted
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // wapLink
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30) // webLink
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SogouPicPojo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDid(cursor.getInt(offset + 1));
        entity.setThumbUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setThumb_width(cursor.getInt(offset + 3));
        entity.setThumb_height(cursor.getInt(offset + 4));
        entity.setSthumbUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSthumb_width(cursor.getInt(offset + 6));
        entity.setSthumb_height(cursor.getInt(offset + 7));
        entity.setBthumbUrl(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setBthumb_width(cursor.getInt(offset + 9));
        entity.setBthumb_height(cursor.getInt(offset + 10));
        entity.setPic_url(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setWidth(cursor.getInt(offset + 12));
        entity.setHeight(cursor.getInt(offset + 13));
        entity.setSize(cursor.getInt(offset + 14));
        entity.setOri_pic_url(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setExt_url(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setPage_title(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setPage_url(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setTitle(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setTags(cursor.isNull(offset + 20) ? null : tagsConverter.convertToEntityProperty(cursor.getString(offset + 20)));
        entity.setGroup_mark(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setGroup_index(cursor.getInt(offset + 22));
        entity.setPublish_time(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setSurr1(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setSurr2(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setCategory(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setWeight(cursor.getInt(offset + 27));
        entity.setDeleted(cursor.getInt(offset + 28));
        entity.setWapLink(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setWebLink(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SogouPicPojo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SogouPicPojo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SogouPicPojo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
